export const TOGGLE_ACCOUNT = 'TOGGLE_ACCOUNT';
export const DATA_FETCH_SUCCEEDED = 'DATA_FETCH_SUCCEEDED';
export const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';
export const DATA_FETCH = 'DATA_FETCH';
