export const TOGGLE_ACCOUNT = 'TOGGLE_ACCOUNT';
export const ACCOUNT_CHANGED = 'ACCOUNT_CHANGED';
export const DATA_FETCH_SUCCEEDED = 'DATA_FETCH_SUCCEEDED';
export const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';
